src/main/c/logging.c
src/main/c/powerwaf_jni.c
src/main/java/io/sqreen/powerwaf/ByteBufferSerializer.java
src/main/java/io/sqreen/powerwaf/CharSequenceWrapper.java
src/main/java/io/sqreen/powerwaf/Powerwaf.java

This drops the memory usage for the JMH benchmark in `dd-trace-java` with 10 headers from ~12k per request to ~4k per request with almost all overhead now being on the AppSec library side.

Optimize memory usage of the native wrapper

---

CMakeLists.txt
build.gradle
src/main/c/json.h
src/main/c/output.c
src/main/c/output.h
src/main/c/powerwaf_jni.c
src/main/c/utf16_utf8.c
src/main/c/utf16_utf8.h
src/main/java/io/sqreen/powerwaf/Powerwaf.java
src/main/java/io/sqreen/powerwaf/RuleSetInfo.java
src/test/groovy/io/sqreen/powerwaf/BadRuleTests.groovy
src/test/groovy/io/sqreen/powerwaf/BasicTests.groovy
src/test/groovy/io/sqreen/powerwaf/InvalidInvocationTests.groovy

Two outputs were changed in 1.11.0:
* ddwaf_init/update now returns diagnostics in a new schema, and in the form of ddwaf_object, rather than the custom struct used before. In this PR, the ddwaf_object is used to create java objects matching the schema of the diagnostics.
* ddwaf_run no longer returns the matches in json, and uses ddwaf_object instead. Here, instead of serializing into a set of java objects, I chose to preserve json output by converting the ddwaf_object into a json string. This is simpler to implement and probably faster, as calling many Java methods from JNI is slow.

Update to version 1.11.0

---

.github/workflows/actions.yml
ci/manylinux/aarch64/Dockerfile

- Uses qemu to run docker containers for arm64. About 10x slower, so we'll be considering other approaches later, but for now this should bring us back to stable builds.
- Moves from `quay.io/pypa/manylinux2010_aarch64` (EOL, no longer available) to `quay.io/pypa/manylinux2014_aarch64`.

Use QEMU for Linux arm64 builds

---

.github/workflows/actions.yml

This will avoid duplicate workflows for every push on a PR.

Run CI on master and PRs, not branches

---

build.gradle
src/main/java/io/sqreen/powerwaf/NativeLibLoader.java

We have some code for loading solaris bindings, but we don't ship them, so just drop it all. There'll be no point in trying to load it.

Drop solaris support code

---

build.gradle

For every operating system, we check jni library and libddwaf, except for macOS, where we were checking for libddwaf debug symbols rather than the library itself.

Fix macos libddwaf path in copy libs task

---

src/main/c/jni/io_sqreen_powerwaf_Powerwaf.h
src/main/c/powerwaf_jni.c
src/main/java/io/sqreen/powerwaf/Powerwaf.java
src/main/java/io/sqreen/powerwaf/PowerwafContext.java
src/test/groovy/io/sqreen/powerwaf/AdditiveTest.groovy

Fixed memory management in WAF bindings to prevent early free memory.
A segmentation fault was identified, stemming from improper memory management. This was due to prematurely closing the lease, which inadvertently allowed the Garbage Collector to free memory still needed to WAF.

Fixed segfault

---

.github/workflows/actions.yml
ci/alpine-libc++-static/aarch64/Dockerfile
ci/alpine-libc++-static/x86_64/Dockerfile

Reduce the amount of back and forth copying of built artifacts, reducing it to just two paths:
* `libddwaf/out` for the intermediate libddwaf build (to be consumed only by Linux bindings build steps)
* `native_libs` for all artifacts to be used by the final gradle build and tests.
* Run Docker containers with the host user and avoid `chown` and any other permission tweaking.

Simplify path handling during CI builds

---

.github/workflows/actions.yml

* Use our arm64 runners for Linux instead of qemu.
* Total pipeline time goes from ~25m to ~6m.
* This runner does not contain any installed tooling. We keep the Docker setup simple at the moment (just default install + `sudo docker`).

Use arm64 runners in GitHub Actions

---

.github/workflows/actions.yml
ci/centos6/Dockerfile

* Split build and test steps.
* Expand job matrix for tests, including various Linux distros, macOS, Windows, JDKs and architectures.
* Some jobs are commented out at the moment due to various issues (noted in the comments).

Split build and test steps

---

.github/workflows/actions.yml

The way we build for development and debugging is significantly different from our release builds. This PR tests our local development workflow as documented in `README.md`. This will help ensuring we do not break it when going for further refactors.

Test development workflows in CI

---

.github/workflows/actions.yml
README.md
build.gradle
ci/static_analysis
src/test/groovy/io/sqreen/powerwaf/LimitsTests.groovy

* Building and running tests with ASAN can now be done with `./gradlew check -PwithASAN`.
* Use the same compiler (gcc) for both libddwaf and libsqreen_jni in the ASAN build job.

Simplify running ASAN locally

---

src/main/java/io/sqreen/powerwaf/Powerwaf.java

Upgrade to [1.16.1](https://github.com/DataDog/libddwaf/releases/tag/1.16.1) patch release for work related to re-using libddwaf builds for libddwaf-java. No need to trigger a release for this since it has no impact with our current build process.

Upgrade to libddwaf 1.16.1

---

.github/workflows/actions.yml
build.gradle
ci/alpine-stock8/Dockerfile
ci/centos6-stock8/Dockerfile
ci/centos6/Dockerfile
ci/centos7-stock8/Dockerfile
ci/ubuntu2204-temurin11/Dockerfile
ci/ubuntu2204-temurin17/Dockerfile
ci/ubuntu2204-temurin21/Dockerfile
ci/ubuntu2204-temurin8/Dockerfile

This allows us to test in setups where our gradle work does not work (e.g. JDK 21, possibly some ARM64 variants, etc). Also enable tests on JDK 21, and Alpine in ARM64.

Split build and test JDKs

---

.github/workflows/actions.yml
build.gradle
ci/ubuntu2204-semeru11/Dockerfile
ci/ubuntu2204-semeru17/Dockerfile
ci/ubuntu2204-semeru21/Dockerfile
ci/ubuntu2204-semeru8/Dockerfile

* We currently have JNI check warnings on J9, so making them non-fatal but adding Semeru JDKs to CI.
* Part of [APPSEC-51927](https://datadoghq.atlassian.net/browse/APPSEC-51927).
* Warnings to be followed up at [APPSEC-52250](https://datadoghq.atlassian.net/browse/APPSEC-52250).
[APPSEC-51927]: https://datadoghq.atlassian.net/browse/APPSEC-51927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APPSEC-52250]: https://datadoghq.atlassian.net/browse/APPSEC-52250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Test on Semeru JDKs

---

.github/workflows/actions.yml

Publish task was broken during last CI refactor, only detected now when trying to release.

Checkout repository in publish task in CI

---

.github/workflows/actions.yml
src/main/java/io/sqreen/powerwaf/Powerwaf.java
src/test/groovy/io/sqreen/powerwaf/BasicTests.groovy

Update libddwaf to 1.18.0
[APPSEC-52825](https://datadoghq.atlassian.net/browse/APPSEC-52825)
[APPSEC-52825]: https://datadoghq.atlassian.net/browse/APPSEC-52825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update to libddwaf 1.18.0

---

.gitlab-ci.yml

Add GitLab job to create package signing keys.
[APPSEC-9858](https://datadoghq.atlassian.net/browse/APPSEC-9858)
[APPSEC-9858]: https://datadoghq.atlassian.net/browse/APPSEC-9858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GitLab job for GPG key creation

---

src/main/c/output.c
src/main/java/io/sqreen/powerwaf/RuleSetInfo.java
src/test/groovy/io/sqreen/powerwaf/BasicTests.groovy

Add support for the `exclusion_data` config object (see [RFC](https://docs.google.com/document/d/123wRO_ha5aZMzIXXJlGHobZrK8F4w5YuzyINncIQVLw/edit)) 
[APPSEC-54438](https://datadoghq.atlassian.net/browse/APPSEC-54438)
[APPSEC-54438]: https://datadoghq.atlassian.net/browse/APPSEC-54438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add support for "exclusion_data"

---

build.gradle
src/main/c/output.c
src/test/groovy/io/sqreen/powerwaf/FingerprintTests.groovy
src/test/groovy/io/sqreen/powerwaf/SchemaTests.groovy

Fix the parsing of the derivatives field from WAF responses. Currently there are two types of derivatives:
- `_dd.appsec.s.`: JSON value with the API schemas that should be gzipped and encoded in base64
- `_dd.appsec.fp.`: strings with the fingerpints

Fix derivatives parsing in the WAF response

---

src/main/java/io/sqreen/powerwaf/Additive.java
src/main/java/io/sqreen/powerwaf/ByteBufferSerializer.java
src/main/java/io/sqreen/powerwaf/PowerwafContext.java
src/main/java/io/sqreen/powerwaf/PowerwafMetrics.java
src/main/java/io/sqreen/powerwaf/metrics/InputTruncatedType.java
src/test/groovy/io/sqreen/powerwaf/ByteBufferSerializerTests.groovy
src/test/groovy/io/sqreen/powerwaf/InvalidInvocationTests.groovy

The main goal of this PR is to improve our observability by including a new type of metric:
- **appsec.waf.input_truncated**: Number of inputs truncated
- _truncation_reason_: Byte with the truncation type
The metric **appsec.waf.truncated_value_size** won't be implemented but some comments will be put in the places where must be added in the future. The main reason is due to the fact that currently distribution metrics are not supported.
Jira ticket: [APPSEC-56479](https://datadoghq.atlassian.net/browse/APPSEC-56479)
[APPSEC-56479]: https://datadoghq.atlassian.net/browse/APPSEC-56479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Create metric: appsec.waf.input_truncated

---

src/main/c/metrics.c
src/main/java/io/sqreen/powerwaf/Additive.java
src/main/java/io/sqreen/powerwaf/PowerwafContext.java
src/main/java/io/sqreen/powerwaf/PowerwafMetrics.java

With this PR we want to refactor current metrics **totalRunTimeNs** and **totalDdwafRunTimeNs** to use **AtomicLong** class instead of **Long**. This will avoid the use of **synchronized** block.
Jira ticket [APPSEC-56479](https://datadoghq.atlassian.net/browse/APPSEC-56479)
[APPSEC-56479]: https://datadoghq.atlassian.net/browse/APPSEC-56479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor metrics: totalRunTimeNs & totalDdwafRunTimeNs

---

README.md
build.gradle

This update integrates the `maven-publish` plugin, allowing the artifact to be published to the local Maven repository. The artifact will be published with a `-SNAPSHOT` suffix based on the version specified in the `build.gradle` script.
To publish to Maven local, use:
```sh
./gradlew publishToMavenLocal
```

Allow publishing to maven local

---

src/main/java/com/datadog/ddwaf/exception/AbstractWafException.java
src/main/java/com/datadog/ddwaf/exception/InternalWafException.java
src/main/java/com/datadog/ddwaf/exception/InvalidArgumentWafException.java
src/main/java/com/datadog/ddwaf/exception/InvalidObjectWafException.java
src/main/java/com/datadog/ddwaf/exception/UnclassifiedWafException.java

Update the error codes used in various exception classes in the `com.datadog.ddwaf.exception` package to ensure consistency with the [RFC](https://docs.google.com/document/d/1D4hkC0jwwUyeo0hEQgyKP54kM1LZU98GL8MaP60tQrA/edit?pli=1&tab=t.0#heading=h.giuqiiuf9z6q)
Allowed error codes are -1, -2, -3 and -127

Fix error codes

---

src/main/java/com/datadog/ddwaf/WafErrorCode.java
src/main/java/com/datadog/ddwaf/exception/AbstractWafException.java
src/main/java/com/datadog/ddwaf/exception/UnclassifiedWafException.java
src/test/groovy/com/datadog/ddwaf/WafErrorCodeTest.groovy
src/test/groovy/com/datadog/ddwaf/exception/AbstractWafExceptionTest.groovy
src/test/groovy/com/datadog/ddwaf/exception/UnclassifiedWafExceptionTest.groovy

- Improves propagation of error codes from native WAF responses
- Ensures bindings return -127 in case of errors before calling into the WAF
- Adds constants for WAF return codes
- Add tests cases

Improve error handling in WAF callbacks

---

.github/workflows/actions.yml
ci/static_analysis

The static analysis job has been broken for a while, presumably after a Clang update. Fix it and use Clang 19. Also split it to a separate job.

Fix static analysis in CI

---

.github/workflows/actions.yml
build.gradle
src/main/c/waf_jni.c
src/main/java/com/datadog/ddwaf/Waf.java
src/test/groovy/com/datadog/ddwaf/ObfuscationTests.groovy

Upgrades libddwaf to 1.25.1, this version removes the ddwaf_result object and advises the use of ddwaf_object
https://github.com/DataDog/libddwaf/blob/master/UPGRADING.md#upgrading-from-124x-to-1250

Upgrade libddwaf to 1.25.1

---

build.gradle
src/main/c/output.c
src/main/c/output.h
src/main/c/waf_jni.c
src/main/java/com/datadog/ddwaf/Waf.java
src/test/groovy/com/datadog/ddwaf/FingerprintTests.groovy
src/test/groovy/com/datadog/ddwaf/RulesCompatTest.groovy
src/test/groovy/com/datadog/ddwaf/SchemaTests.groovy
src/test/groovy/com/datadog/ddwaf/WafContextTest.groovy

[APPSEC-57260](https://datadoghq.atlassian.net/browse/APPSEC-57260)
[APPSEC-57260]: https://datadoghq.atlassian.net/browse/APPSEC-57260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
derivatives are mapped to attributes with the new libddwaf version
When libddwaf returns keep, we have to flag the attribute manual-keep
events, consists in an array of events generated as a result of the rule evaluation process.
actions consists in a map of the actions, and their parameters, generated as a result of the rule evaluation process.
all three of these must be exposed to the tracer for us to be able to evaluate libddwaf results
rules_compat is a temporary attribute that holds the new rules return for libddwaf. this will eventually be merged to the …

Map keep and events object to use in tracer, return rules_compat output

---

.github/workflows/actions.yml
build.gradle
src/main/java/com/datadog/ddwaf/Waf.java
src/test/groovy/com/datadog/ddwaf/BadRuleTests.groovy
src/test/groovy/com/datadog/ddwaf/BasicTests.groovy

APPSEC-58796
statuses are now longs

Upgrading libddwaf to 1.28.0
